#! python3

import time

def calcProd():
	# calc tbe product of the first 100k nums

	product = 1
	for i in range(1, 100000):
		product = product * i

	return product

startTime = time.time()
prod = calcProd()
endTime = time.time()
print('Result is %s digits long.' % (len(str(prod))))
print('Took %s seconds to calculate,' % (endTime - startTime)) 
##print('Product =  %s' % prod)